export const GlobalStateActionType = {

  FETCH_STATE: 'SET_STATE',
  FETCH_DISTRICT: 'SET_DISTRICT',
  FETCH_OFFICE: 'SET_OFFICE',
  FETCH_MODULE: 'SET_MODULE',
  FETCH_STAGE: 'SET_STAGE',
  FETCH_STATUS: 'SET_STATUS',
  FETCH_OFFICER_STAGE: 'SET_OFFICER_STAGE',



  SET_STATE: 'SET_STATE',
  SET_DISTRICT: 'SET_DISTRICT',
  SET_OFFICE: 'SET_OFFICE',
  SET_MODULE: 'SET_MODULE',
  SET_STAGE: 'SET_STAGE',
  SET_STATUS: 'SET_STATUS',
  SET_OFFICER_STAGE: 'SET_OFFICER_STAGE',

  SET_STATE_ERROR: 'SET_STATE_ERROR',
  SET_DISTRICT_ERROR: 'SET_DISTRICT_ERROR',
  SET_OFFICE_ERROR: 'SET_OFFICE_ERROR',
  SET_MODULE_ERROR: 'SET_MODULE_ERROR',
  SET_STAGE_ERROR: 'SET_STAGE_ERROR',
  SET_STATUS_ERROR: 'SET_STATUS_ERROR',
  SET_OFFICER_STAGE_ERROR: 'SET_OFFICER_STAGE_ERROR'
} 